<a href="https://colab.research.google.com/github/Greta-gerasimov/Project_libraries/blob/dev/numpy_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🍪1

In [ ]:
import numpy as np


In [ ]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
a_mean = a.mean(axis=0)
a_mean

array([2. , 8.4])

🍪2

In [ ]:
a_centered = np.subtract(a,a_mean)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

🍪3

In [ ]:
row1 = np.array((a_centered[0:6, 0:1].copy()),
                           dtype = int)
row2 = np.array((a_centered[0:6 ,1:2].copy()),
                           dtype = int)

print(row1)


[[-1]
 [ 0]
 [ 1]
 [ 1]
 [-1]]


In [ ]:
row2.shape

(5, 1)

In [ ]:
print(row2)

[[-2]
 [ 0]
 [ 2]
 [ 1]
 [-1]]


транспонирование матрицы разными способами:

In [ ]:
#1
a_T=np.array([[1,6],[2,8],[3,11],[3,10],[1,7]]).T
print(a_T)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [ ]:
#2
row1_T = np.transpose(row1)
print(row1_T)


[[-1  0  1  1 -1]]


In [ ]:
!pip install pymatrix

  Created wheel for pymatrix: filename=pymatrix-3.0.1-py3-none-any.whl size=7061 sha256=b1c8db3a3105fb3bec91654ac729931f523f17af8a40323b2c08bef73770a96f
  Stored in directory: /root/.cache/pip/wheels/0b/f6/fb/48658698ba9d602d6a134df6405d80ddc336c63585cf649bd0
Successfully built pymatrix


In [ ]:
#3
import pymatrix
matrix= pymatrix.matrix([[-1],[0],[1],[1],[-1]])
row1__T = matrix.trans()
print(f'транспонированная матрица: \n {row1__T}')

транспонированная матрица: 
 -1  0  1  1 -1


In [ ]:
a_centered_sp = row1_T @ row2
print(a_centered_sp)

[[6]]


In [ ]:
print(f'\n скалярное произведение столбцов:\n a_centered_sp:\n {a_centered_sp}')


 скалярное произведение столбцов:
 a_centered_sp:
 [[6]]


In [ ]:
#количество строк(наблюдений):
rows = len(a)
print(rows)


5


In [ ]:
z = a_centered_sp * (1/(rows-1))
print(z)


[[1.5]]


In [ ]:
covMatrix = np.cov(a_T,bias=True)
print (covMatrix)


[[0.8  1.6 ]
 [1.6  3.44]]
