<a href="https://colab.research.google.com/github/Greta-gerasimov/Project_libraries/blob/HW_2/repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
a = np.linspace(12, 23, num =  12)

print(a)
print(a.shape)


[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
(12,)


In [3]:
#2
b = a.reshape(3, 4)
c = a.reshape(4, 3)
f = a.reshape(2, 6)
d = a.reshape(6, 2)
e = a.reshape(1, 12)
print(b)
print(c)
print(f)
print(d)
print(e)

[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
[[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]]


In [5]:
#3
b = a.reshape(12, -1)
c = a.reshape(4, -1)
f = a.reshape(2, -1)
d = a.reshape(-1, 4)
e = a.reshape(-1, 3)
print(b)
print(c)
print(f)
print(d)
print(e)

[[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


In [10]:
#5
a = np.random.rand(3,4)
a1 = np.array(a,dtype=np.float64)
print(a1)
print(a)
print(a.size)
# как сделать нормальное распределение со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.???
c = a.flatten()
print(c)
print(c.size)

[[0.81242353 0.43060076 0.14167103 0.59553626]
 [0.8885183  0.90860321 0.50045604 0.79195771]
 [0.50728553 0.36962442 0.49886611 0.87328403]]
[[0.81242353 0.43060076 0.14167103 0.59553626]
 [0.8885183  0.90860321 0.50045604 0.79195771]
 [0.50728553 0.36962442 0.49886611 0.87328403]]
12
[0.81242353 0.43060076 0.14167103 0.59553626 0.8885183  0.90860321
 0.50045604 0.79195771 0.50728553 0.36962442 0.49886611 0.87328403]
12


In [11]:
#6
a = np.arange(20, 0, -2)
print(a)


[20 18 16 14 12 10  8  6  4  2]


In [12]:
#7
b = np.arange(20, 1, -2).reshape(1,10)
print(b)
#нужно ли дополнительно указывать, что это целые числа?

[[20 18 16 14 12 10  8  6  4  2]]


In [ ]:
#разница между массивом a и b состоит в том, первый массив - одномерный(состоит из одной строки),
# а второй - двумерный(состоит из какого-то вполне определенного числа строк и столбцов, что определяется методом reshape(меняет размерность))

In [13]:
#массив a - двумерный из нулей, число строк которого больше чем 1 и на 1 меньше, чем в массиве b

a = np.zeros((2, 2))
print(a)

b = np.ones((3, 2))
print(b)

#обьединить  вертикально массивы a + b  = v
#v.size = 10
v = np.vstack((a, b))
print(v)
v.size


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [14]:
#9
a = np.arange(0, 12)
print(a)

A = a.reshape(4,3)
print(A)

At =  np.transpose(A)
print(At)

B  = np.dot(A,At)
print(B)
B.shape

B_inv=np.linalg.inv(B)
print(B_inv)
#Singular matrix

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


LinAlgError: ignored

In [16]:
#10.Генератор случайных чисел(42)

import random
random.seed(42)
print(random.random())

for i in range(5):
    random.seed(11)
    print(random.randint(1, 1000))


0.6394267984578837
464
464
464
464
464


In [17]:
#11
c = np.random.randint(0, 15, 16)
print(c)

[ 9 12  1  0  9  8  5 13 13  2  8  2  1  1 13  3]


In [19]:

#12-13.
C = c.reshape(4, 4)
print(C)
k = 10
D = B+(C*k)
print(D)
print(f'Определитель:\n{np.linalg.det(D):.0f}')
print(f'Ранг:\n{np.linalg.matrix_rank(D)}')
#обратная матрица D
D_inv=np.linalg.inv(D)
print(D_inv)
D_inv=np.where(D_inv<0, 0, 1)
print(D_inv)

[[ 9 12  1  0]
 [ 9  8  5 13]
 [13  2  8  2]
 [ 1  1 13  3]]
[[ 95 134  33  32]
 [104 130 136 252]
 [153 106 229 232]
 [ 42 132 342 332]]
Определитель:
-543986000
Ранг:
4
[[-0.00085612 -0.00073958  0.0091484  -0.00574897]
 [ 0.00888714  0.00055715 -0.00686194  0.00351561]
 [ 0.00164379 -0.00838845  0.00368355  0.00363465]
 [-0.00511844  0.00851316 -0.00222359 -0.00140257]]
[[0 0 1 0]
 [1 1 0 1]
 [1 0 1 1]
 [0 1 0 0]]


In [20]:
print(B)
print(C)
E=np.where(D_inv==1, B, C)
print(E)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 9 12  1  0]
 [ 9  8  5 13]
 [13  2  8  2]
 [ 1  1 13  3]]
[[  9  12  23   0]
 [ 14  50   5 122]
 [ 23   2 149 212]
 [  1 122  13   3]]
